version: "3.9"

services:
  mysql_service:
    image: mysql:8.0
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  zenml_service:
    image: zenmldocker/zenml-server
    ports:
      - "${ZENML_PORT}:8080"
    environment:
      - ZENML_STORE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql_service/${MYSQL_DATABASE}
    links:
      - mysql_service
    depends_on:
      - mysql_service
    extra_hosts:
      - mysql_service:host-gateway
    restart: on-failure
  mlflow_service:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - ${MLFLOW_PORT}:5000
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root ${MLFLOW_ARTIFACT_PATH}
      --host ${MLFLOW_HOST}
      --port ${MLFLOW_PORT}
    restart: on-failure
    volumes:
      - mlflow_data:/mlflow

volumes:
  mlflow_data: {}
  mysql_data: {}
